
class ResultCodes():

    ERROR_USERNAME_LENGTH_INVALID    = 'INVALID_USERNAME_LENGTH'
    ERROR_PASSWORD_LENGTH_INVALID    = 'INVALID_PASSWORD_LENGTH'
    ERROR_INVALID_USERNAME_CHARS     = 'INVALID_USERNAME_CHARS'
    ERROR_DUPLICATE_USERNAME         = 'DUPLICATE_USERNAME'
    ERROR_EMPTY_USERNAME             = 'EMPTY_USERNAME'
    ERROR_EMPTY_PASSWORD             = 'EMPTY_PASSWORD'
    ERROR_EMPTY_FIELDS               = 'EMPTY_FIELDS'
    SUCCESS_USERNAME_PASSWORD_LENGTH = 'GOOD_USERNAME_&_PASSWORD_LENGTH'
    SUCCESS_FIELDS_FILLED            = 'ALL_FIELDS_FILLED'
    SUCCESS                          = 'SUCCESS'
